export const LOGGING_IN = 'LOGGING_IN';
export const LOGGED_IN = 'LOGGED_IN';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const LOGGING_OUT = 'LOGGING_OUT';
export const LOGGED_OUT = 'LOGGED_OUT';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';

export const ADD_ERROR = 'ADD_ERROR';
export const REMOVE_ERROR = 'REMOVE_ERROR';

export const PROFILE_LOADING = 'PROFILE_LOADING';
export const PROFILE_FAILED = 'PROFILE_FAILED';
export const PROFILE_FETCHED = 'PROFILE_FETCHED';
export const PROFILE_RESET = 'PROFILE_RESET';

export const SIGNING_UP = 'SIGNING_UP';
export const SIGNUP_SUCCESSFUL = 'SIGNUP_SUCCESSFUL';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';
export const SIGNUP_RESET = 'SIGNUP_RESET';

export const EXPENSES_LOADING = 'EXPENSES_LOADING';
export const EXPENSES_FAILED = 'EXPENSES_FAILED';
export const EXPENSES_FETCHED = 'EXPENSES_FETCHED';
export const EXPENSES_RESET = 'EXPENSES_RESET';

export const ADDING_EXP = 'ADDING_EXP';
export const EXP_ADDED = 'EXP_ADDED';
export const EXP_FAILED = 'SIGNUP_FAILED';
export const EXP_RESET = 'EXP_RESET';